package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AlumnoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoAllPropertiesEquals(Alumno expected, Alumno actual) {
        assertAlumnoAutoGeneratedPropertiesEquals(expected, actual);
        assertAlumnoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoAllUpdatablePropertiesEquals(Alumno expected, Alumno actual) {
        assertAlumnoUpdatableFieldsEquals(expected, actual);
        assertAlumnoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoAutoGeneratedPropertiesEquals(Alumno expected, Alumno actual) {
        assertThat(actual)
            .as("Verify Alumno auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoUpdatableFieldsEquals(Alumno expected, Alumno actual) {
        assertThat(actual)
            .as("Verify Alumno relevant properties")
            .satisfies(a -> assertThat(a.getDni()).as("check dni").isEqualTo(expected.getDni()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()))
            .satisfies(a -> assertThat(a.getTipoAlumno()).as("check tipoAlumno").isEqualTo(expected.getTipoAlumno()))
            .satisfies(a ->
                assertThat(a.getNotaPromedio())
                    .as("check notaPromedio")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getNotaPromedio())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoUpdatableRelationshipsEquals(Alumno expected, Alumno actual) {
        // empty method
    }
}
