package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfesorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesorAllPropertiesEquals(Profesor expected, Profesor actual) {
        assertProfesorAutoGeneratedPropertiesEquals(expected, actual);
        assertProfesorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesorAllUpdatablePropertiesEquals(Profesor expected, Profesor actual) {
        assertProfesorUpdatableFieldsEquals(expected, actual);
        assertProfesorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesorAutoGeneratedPropertiesEquals(Profesor expected, Profesor actual) {
        assertThat(actual)
            .as("Verify Profesor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesorUpdatableFieldsEquals(Profesor expected, Profesor actual) {
        assertThat(actual)
            .as("Verify Profesor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesorUpdatableRelationshipsEquals(Profesor expected, Profesor actual) {
        // empty method
    }
}
